# Generated by Django 5.0.1 on 2024-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='идентификатор оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка оплаты'),
        ),
    ]
