# Generated by Django 5.0.1 on 2024-01-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscriptionsuseroncourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pk'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
